services:

  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"

  gateway:
    build: ./gateway
    ports:
      - ${GATEWAY_PORT}:3000
    volumes:
      - ./gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  administrative-data-ms:
    build: ./administrative-data-ms
    volumes:
      - ./administrative-data-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${DIRECT_URL_ADMINISTRATIVE_DATA_DB}
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
  
  users-ms:
    build: ./users-ms
    volumes:
      - ./users-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${DIRECT_URL_USERS_DB}

  trajectory-ms:
    build: ./trajectory-ms
    volumes:
      - ./trajectory-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${DIRECT_URL_TRAJECTORY_DB}